module Analytics
  class PrinterStats
    attr_reader :user, :start_date, :end_date

    def initialize(user, start_date: nil, end_date: nil)
      @user = user
      @end_date = end_date || Date.current
      @start_date = start_date || 30.days.ago.to_date
    end

    # Printer utilization metrics
    def printer_usage_stats
      @printer_usage_stats ||= user.printers.map do |printer|
        pricings = current_period_pricings.where(printer: printer)
        total_print_time = pricings.sum { |p| p.total_actual_print_time_minutes * p.times_printed }
        total_prints = pricings.sum(:times_printed)

        # Calculate utilization percentage based on days in period
        days_in_period = (end_date - start_date).to_i + 1
        available_minutes = days_in_period * printer.daily_usage_hours * 60
        utilization_rate = available_minutes > 0 ? (total_print_time.to_f / available_minutes * 100).round(1) : 0

        {
          printer: printer,
          total_print_time_hours: (total_print_time / 60.0).round(1),
          total_prints: total_prints,
          utilization_rate: utilization_rate,
          revenue: pricings.sum { |p| p.final_price * p.times_printed }
        }
      end.sort_by { |stat| -stat[:revenue] }
    end

    # ROI tracking for all printers
    def roi_progress
      @roi_progress ||= user.printers.map do |printer|
        {
          printer: printer,
          paid_off: printer.paid_off?,
          months_to_payoff: printer.months_to_payoff,
          progress_percentage: calculate_roi_progress(printer)
        }
      end
    end

    # Cost per print by printer
    def cost_per_print_by_printer
      @cost_per_print_by_printer ||= user.printers.map do |printer|
        pricings = current_period_pricings.where(printer: printer)
        total_prints = pricings.sum(:times_printed)
        total_cost = pricings.sum { |p| p.calculate_subtotal * p.times_printed }

        {
          printer: printer,
          cost_per_print: total_prints > 0 ? (total_cost / total_prints.to_f).round(2) : 0,
          total_prints: total_prints
        }
      end.sort_by { |stat| stat[:printer].name }
    end

    # Most used printer
    def most_used_printer
      stats = printer_usage_stats
      stats.max_by { |stat| stat[:total_print_time_hours] }
    end

    # Average utilization rate across all printers
    def average_utilization_rate
      stats = printer_usage_stats
      return 0 if stats.empty?

      total_utilization = stats.sum { |stat| stat[:utilization_rate] }
      (total_utilization / stats.size.to_f).round(1)
    end

    private

    def current_period_pricings
      @current_period_pricings ||= user.print_pricings
        .includes(:plates, :printer)
        .where(created_at: start_date.beginning_of_day..end_date.end_of_day)
    end

    def calculate_roi_progress(printer)
      return 100 if printer.paid_off?
      return 0 unless printer.cost && printer.payoff_goal_years && printer.daily_usage_hours

      # Calculate total revenue generated by this printer
      total_revenue = user.print_pricings
        .where(printer: printer)
        .sum { |p| p.final_price * p.times_printed }

      # Calculate progress percentage
      progress = (total_revenue / printer.cost.to_f * 100).round(1)
      [ progress, 100 ].min # Cap at 100%
    end
  end
end
